name: Continuous Integration

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: zulu@1.17.0-0

      - name: Build project
        run: sbt ++${{ matrix.scala }} test

      - name: Compile examples
        run: sbt examples/compile
docs:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
      - run: sbt '++2.13.15 docs/mdoc'
